ALTER TABLE bulk_deliveries
ADD COLUMN date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE consumer_deliveries
ADD COLUMN date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
